pipeline:
  backend:
    group: build
    image: golang
    commands:
      - go get
      - CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o ./main ./*.go
      - go test
  publish:
    image: plugins/docker
    repo: docker.benjaminbaedorf.eu/b12f/lnb-server
    registry: docker.benjaminbaedorf.eu
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      branch: master
      status: success