pipeline:
  clone:
    image: plugins/git
  backend:
    group: build
    image: golang
    environment:
      - CGO=0
      - GOOS=linux
    commands:
      - go get
      - go build -a -installsuffix cgo -o ./main ./*.go
      - go test
  publish:
    image: plugins/docker
    repo: docker.benjaminbaedorf.eu/b12f/lnb-server
    registry: docker.benjaminbaedorf.eu
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      branch: master
      status: success