workspace:
  base: /go
  path: src/git.benjaminbaedorf.eu/b12f/lnb-server

pipeline:
  build:
    image: golang:1.8
    environment:
      - CGO=0
      - GOOS=linux
    commands:
      - go get
      - go build -a -installsuffix cgo -o ./main ./*.go
      - go test
  publish:
    image: plugins/docker
    repo: docker.benjaminbaedorf.eu/b12f/lnb-server
    tags: $$DRONE_TAG
    registry: docker.benjaminbaedorf.eu
    secrets: [ docker_username, docker_password ]
    when:
      event: tag
      status: success